import { Question } from "@/lib/types/question";

export const grade5Questions: Question[] = [
  {
    id: "g5-001",
    grade: 5,
    sentence: "法案が（かけつ）される。",
    answer: "可決",
    reading: "かけつ",
    readingPerChar: ["か", "けつ"],
  },
  {
    id: "g5-002",
    grade: 5,
    sentence: "（かめん）をつける。",
    answer: "仮面",
    reading: "かめん",
    readingPerChar: ["か", "めん"],
  },
  {
    id: "g5-003",
    grade: 5,
    sentence: "（えいぎょうじかん）を確認する。",
    answer: "営業時間",
    reading: "えいぎょうじかん",
    readingPerChar: ["えい", "ぎょう", "じ", "かん"],
  },
  {
    id: "g5-004",
    grade: 5,
    sentence: "役者が（えんぎ）する。",
    answer: "演技",
    reading: "えんぎ",
    readingPerChar: ["えん", "ぎ"],
  },
  {
    id: "g5-005",
    grade: 5,
    sentence: "学校と家を（おうふく）する。",
    answer: "往復",
    reading: "おうふく",
    readingPerChar: ["おう", "ふく"],
  },
  {
    id: "g5-006",
    grade: 5,
    sentence: "川の（かこう）を探す。",
    answer: "河口",
    reading: "かこう",
    readingPerChar: ["か", "こう"],
  },
  {
    id: "g5-007",
    grade: 5,
    sentence: "失敗の（げんいん）を調べる。",
    answer: "原因",
    reading: "げんいん",
    readingPerChar: ["げん", "いん"],
  },
  {
    id: "g5-008",
    grade: 5,
    sentence: "商売で（りえき）を得る。",
    answer: "利益",
    reading: "りえき",
    readingPerChar: ["り", "えき"],
  },
  {
    id: "g5-009",
    grade: 5,
    sentence: "（えきたい）をこぼす。",
    answer: "液体",
    reading: "えきたい",
    readingPerChar: ["えき", "たい"],
  },
  {
    id: "g5-010",
    grade: 5,
    sentence: "教室へ（いどう）する。",
    answer: "移動",
    reading: "いどう",
    readingPerChar: ["い", "どう"],
  },
  {
    id: "g5-011",
    grade: 5,
    sentence: "外国と（こうえき）をする。",
    answer: "交易",
    reading: "こうえき",
    readingPerChar: ["こう", "えき"],
  },
  {
    id: "g5-012",
    grade: 5,
    sentence: "（えいえん）に続く。",
    answer: "永遠",
    reading: "えいえん",
    readingPerChar: ["えい", "えん"],
  },
  {
    id: "g5-013",
    grade: 5,
    sentence: "（じんこうえいせい）を打ち上げる。",
    answer: "人工衛星",
    reading: "じんこうえいせい",
    readingPerChar: ["じん", "こう", "えい", "せい"],
  },
  {
    id: "g5-014",
    grade: 5,
    sentence: "（さくら）が満開だ。",
    answer: "桜",
    reading: "さくら",
    readingPerChar: ["さくら"],
  },
  {
    id: "g5-015",
    grade: 5,
    sentence: "（あつりょく）が高い。",
    answer: "圧力",
    reading: "あつりょく",
    readingPerChar: ["あつ", "りょく"],
  },
  {
    id: "g5-016",
    grade: 5,
    sentence: "（ぶっか）が上がる。",
    answer: "物価",
    reading: "ぶっか",
    readingPerChar: ["ぶつ", "か"],
  },
  {
    id: "g5-017",
    grade: 5,
    sentence: "（しゅうい）を見わたす。",
    answer: "周囲",
    reading: "しゅうい",
    readingPerChar: ["しゅう", "い"],
  },
  {
    id: "g5-018",
    grade: 5,
    sentence: "雑誌を（かんこう）する。",
    answer: "刊行",
    reading: "かんこう",
    readingPerChar: ["かん", "こう"],
  },
  {
    id: "g5-019",
    grade: 5,
    sentence: "問題を（かいけつ）した。",
    answer: "解決",
    reading: "かいけつ",
    readingPerChar: ["かい", "けつ"],
  },
  {
    id: "g5-020",
    grade: 5,
    sentence: "（かくじつ）な作業。",
    answer: "確実",
    reading: "かくじつ",
    readingPerChar: ["かく", "じつ"],
  },
];